sudo: false
dist: trusty
language: php
php:
  - 5.6
  - 7.0
env:
  - TEST_SUITE=unit
cache:
  apt: true
  directories: $HOME/.composer/cache
install: composer install --no-interaction --prefer-dist
script: 
  - phpunit vendor/wojtekn/magento2-cron-manager/Test
